### PR TITLE
Skip tests that require an Akismet key unless one is set in ENV

### LINKED ISSUE #297: Test suite is broken
Since https://github.com/denny/ShinyCMS-ruby/commit/2925f44514e5919f9ff3152d1ff66790167cce61 tests don't pass anymore in a fresh setup:

```
± |master → origin U:1 ✗| → rspec

Randomized with seed 26662
..............................................................................*.*.............................................................................FF.F.............................................................................................

Pending: (Failures listed here are expected and do not affect your suite's status)

  1) Discussions/Comments POST /discussion/1 classifies a new comment as spam after checking Akismet
     # Valid Akismet API KEY required
     # ./spec/requests/discussions_spec.rb:231

  2) Discussions/Comments POST /discussion/1 doesn't save a new comment if Akismet classifies it as 'blatant' spam
     # Valid Akismet API KEY required
     # ./spec/requests/discussions_spec.rb:260


Failures:

  1) Comment moderation PUT /admin/comments removes spam flags from the selected comments if you say they are not spam
     Failure/Error: client.open
     
     SocketError:
       Failed to open TCP connection to .rest.akismet.com:443 (getaddrinfo: Name or service not known)
     # /home/lvargas/.gem/ruby/2.6.6/gems/akismet-3.0.0/lib/akismet/client.rb:101:in `open'
     # ./app/helpers/akismet_helper.rb:23:in `akismet_client'
     # ./app/helpers/akismet_helper.rb:49:in `akismet_flag_as_ham'
     # ./app/controllers/admin/comments_controller.rb:98:in `process_ham_comments'
     # ./app/controllers/admin/comments_controller.rb:34:in `update'
     # /home/lvargas/.gem/ruby/2.6.6/gems/ahoy_matey-3.0.3/lib/ahoy/controller.rb:45:in `set_ahoy_request_store'
     # /home/lvargas/.gem/ruby/2.6.6/gems/warden-1.2.8/lib/warden/manager.rb:36:in `block in call'
     # /home/lvargas/.gem/ruby/2.6.6/gems/warden-1.2.8/lib/warden/manager.rb:34:in `catch'
     # /home/lvargas/.gem/ruby/2.6.6/gems/warden-1.2.8/lib/warden/manager.rb:34:in `call'
     # /home/lvargas/.gem/ruby/2.6.6/gems/rack-2.2.2/lib/rack/tempfile_reaper.rb:15:in `call'
     # /home/lvargas/.gem/ruby/2.6.6/gems/rack-2.2.2/lib/rack/etag.rb:27:in `call'
     # /home/lvargas/.gem/ruby/2.6.6/gems/rack-2.2.2/lib/rack/conditional_get.rb:40:in `call'
     # /home/lvargas/.gem/ruby/2.6.6/gems/rack-2.2.2/lib/rack/head.rb:12:in `call'
     # /home/lvargas/.gem/ruby/2.6.6/gems/rack-2.2.2/lib/rack/session/abstract/id.rb:266:in `context'
     # /home/lvargas/.gem/ruby/2.6.6/gems/rack-2.2.2/lib/rack/session/abstract/id.rb:260:in `call'
     # /home/lvargas/.gem/ruby/2.6.6/gems/railties-6.0.2.2/lib/rails/rack/logger.rb:38:in `call_app'
     # /home/lvargas/.gem/ruby/2.6.6/gems/railties-6.0.2.2/lib/rails/rack/logger.rb:26:in `block in call'
     # /home/lvargas/.gem/ruby/2.6.6/gems/railties-6.0.2.2/lib/rails/rack/logger.rb:26:in `call'
     # /home/lvargas/.gem/ruby/2.6.6/gems/ahoy_matey-3.0.3/lib/ahoy/engine.rb:22:in `call_with_quiet_ahoy'
     # /home/lvargas/.gem/ruby/2.6.6/gems/request_store-1.5.0/lib/request_store/middleware.rb:19:in `call'
     # /home/lvargas/.gem/ruby/2.6.6/gems/rack-2.2.2/lib/rack/method_override.rb:24:in `call'
     # /home/lvargas/.gem/ruby/2.6.6/gems/rack-2.2.2/lib/rack/runtime.rb:22:in `call'
     # /home/lvargas/.gem/ruby/2.6.6/gems/rack-2.2.2/lib/rack/sendfile.rb:110:in `call'
     # /home/lvargas/.gem/ruby/2.6.6/gems/railties-6.0.2.2/lib/rails/engine.rb:526:in `call'
     # /home/lvargas/.gem/ruby/2.6.6/gems/rack-test-1.1.0/lib/rack/mock_session.rb:29:in `request'
     # /home/lvargas/.gem/ruby/2.6.6/gems/rack-test-1.1.0/lib/rack/test.rb:266:in `process_request'
     # /home/lvargas/.gem/ruby/2.6.6/gems/rack-test-1.1.0/lib/rack/test.rb:119:in `request'
     # ./spec/requests/admin/comments_spec.rb:97:in `block (3 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # SocketError:
     #   getaddrinfo: Name or service not known
     #   /home/lvargas/.gem/ruby/2.6.6/gems/akismet-3.0.0/lib/akismet/client.rb:101:in `open'

  2) Comment moderation PUT /admin/comments deletes the selected comments if you say they are spam
     Failure/Error: client.open
     
     SocketError:
       Failed to open TCP connection to .rest.akismet.com:443 (getaddrinfo: Name or service not known)
     # /home/lvargas/.gem/ruby/2.6.6/gems/akismet-3.0.0/lib/akismet/client.rb:101:in `open'
     # ./app/helpers/akismet_helper.rb:23:in `akismet_client'
     # ./app/helpers/akismet_helper.rb:37:in `akismet_confirm_spam'
     # ./app/controllers/admin/comments_controller.rb:92:in `process_spam_comments'
     # ./app/controllers/admin/comments_controller.rb:32:in `update'
     # /home/lvargas/.gem/ruby/2.6.6/gems/ahoy_matey-3.0.3/lib/ahoy/controller.rb:45:in `set_ahoy_request_store'
     # /home/lvargas/.gem/ruby/2.6.6/gems/warden-1.2.8/lib/warden/manager.rb:36:in `block in call'
     # /home/lvargas/.gem/ruby/2.6.6/gems/warden-1.2.8/lib/warden/manager.rb:34:in `catch'
     # /home/lvargas/.gem/ruby/2.6.6/gems/warden-1.2.8/lib/warden/manager.rb:34:in `call'
     # /home/lvargas/.gem/ruby/2.6.6/gems/rack-2.2.2/lib/rack/tempfile_reaper.rb:15:in `call'
     # /home/lvargas/.gem/ruby/2.6.6/gems/rack-2.2.2/lib/rack/etag.rb:27:in `call'
     # /home/lvargas/.gem/ruby/2.6.6/gems/rack-2.2.2/lib/rack/conditional_get.rb:40:in `call'
     # /home/lvargas/.gem/ruby/2.6.6/gems/rack-2.2.2/lib/rack/head.rb:12:in `call'
     # /home/lvargas/.gem/ruby/2.6.6/gems/rack-2.2.2/lib/rack/session/abstract/id.rb:266:in `context'
     # /home/lvargas/.gem/ruby/2.6.6/gems/rack-2.2.2/lib/rack/session/abstract/id.rb:260:in `call'
     # /home/lvargas/.gem/ruby/2.6.6/gems/railties-6.0.2.2/lib/rails/rack/logger.rb:38:in `call_app'
     # /home/lvargas/.gem/ruby/2.6.6/gems/railties-6.0.2.2/lib/rails/rack/logger.rb:26:in `block in call'
     # /home/lvargas/.gem/ruby/2.6.6/gems/railties-6.0.2.2/lib/rails/rack/logger.rb:26:in `call'
     # /home/lvargas/.gem/ruby/2.6.6/gems/ahoy_matey-3.0.3/lib/ahoy/engine.rb:22:in `call_with_quiet_ahoy'
     # /home/lvargas/.gem/ruby/2.6.6/gems/request_store-1.5.0/lib/request_store/middleware.rb:19:in `call'
     # /home/lvargas/.gem/ruby/2.6.6/gems/rack-2.2.2/lib/rack/method_override.rb:24:in `call'
     # /home/lvargas/.gem/ruby/2.6.6/gems/rack-2.2.2/lib/rack/runtime.rb:22:in `call'
     # /home/lvargas/.gem/ruby/2.6.6/gems/rack-2.2.2/lib/rack/sendfile.rb:110:in `call'
     # /home/lvargas/.gem/ruby/2.6.6/gems/railties-6.0.2.2/lib/rails/engine.rb:526:in `call'
     # /home/lvargas/.gem/ruby/2.6.6/gems/rack-test-1.1.0/lib/rack/mock_session.rb:29:in `request'
     # /home/lvargas/.gem/ruby/2.6.6/gems/rack-test-1.1.0/lib/rack/test.rb:266:in `process_request'
     # /home/lvargas/.gem/ruby/2.6.6/gems/rack-test-1.1.0/lib/rack/test.rb:119:in `request'
     # ./spec/requests/admin/comments_spec.rb:69:in `block (3 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # SocketError:
     #   getaddrinfo: Name or service not known
     #   /home/lvargas/.gem/ruby/2.6.6/gems/akismet-3.0.0/lib/akismet/client.rb:101:in `open'

  3) Comment moderation PUT /admin/comments reports an error if it fails to remove spam flags
     Failure/Error: client.open
     
     SocketError:
       Failed to open TCP connection to .rest.akismet.com:443 (getaddrinfo: Name or service not known)
     # /home/lvargas/.gem/ruby/2.6.6/gems/akismet-3.0.0/lib/akismet/client.rb:101:in `open'
     # ./app/helpers/akismet_helper.rb:23:in `akismet_client'
     # ./app/helpers/akismet_helper.rb:49:in `akismet_flag_as_ham'
     # ./app/controllers/admin/comments_controller.rb:98:in `process_ham_comments'
     # ./app/controllers/admin/comments_controller.rb:34:in `update'
     # /home/lvargas/.gem/ruby/2.6.6/gems/ahoy_matey-3.0.3/lib/ahoy/controller.rb:45:in `set_ahoy_request_store'
     # /home/lvargas/.gem/ruby/2.6.6/gems/warden-1.2.8/lib/warden/manager.rb:36:in `block in call'
     # /home/lvargas/.gem/ruby/2.6.6/gems/warden-1.2.8/lib/warden/manager.rb:34:in `catch'
     # /home/lvargas/.gem/ruby/2.6.6/gems/warden-1.2.8/lib/warden/manager.rb:34:in `call'
     # /home/lvargas/.gem/ruby/2.6.6/gems/rack-2.2.2/lib/rack/tempfile_reaper.rb:15:in `call'
     # /home/lvargas/.gem/ruby/2.6.6/gems/rack-2.2.2/lib/rack/etag.rb:27:in `call'
     # /home/lvargas/.gem/ruby/2.6.6/gems/rack-2.2.2/lib/rack/conditional_get.rb:40:in `call'
     # /home/lvargas/.gem/ruby/2.6.6/gems/rack-2.2.2/lib/rack/head.rb:12:in `call'
     # /home/lvargas/.gem/ruby/2.6.6/gems/rack-2.2.2/lib/rack/session/abstract/id.rb:266:in `context'
     # /home/lvargas/.gem/ruby/2.6.6/gems/rack-2.2.2/lib/rack/session/abstract/id.rb:260:in `call'
     # /home/lvargas/.gem/ruby/2.6.6/gems/railties-6.0.2.2/lib/rails/rack/logger.rb:38:in `call_app'
     # /home/lvargas/.gem/ruby/2.6.6/gems/railties-6.0.2.2/lib/rails/rack/logger.rb:26:in `block in call'
     # /home/lvargas/.gem/ruby/2.6.6/gems/railties-6.0.2.2/lib/rails/rack/logger.rb:26:in `call'
     # /home/lvargas/.gem/ruby/2.6.6/gems/ahoy_matey-3.0.3/lib/ahoy/engine.rb:22:in `call_with_quiet_ahoy'
     # /home/lvargas/.gem/ruby/2.6.6/gems/request_store-1.5.0/lib/request_store/middleware.rb:19:in `call'
     # /home/lvargas/.gem/ruby/2.6.6/gems/rack-2.2.2/lib/rack/method_override.rb:24:in `call'
     # /home/lvargas/.gem/ruby/2.6.6/gems/rack-2.2.2/lib/rack/runtime.rb:22:in `call'
     # /home/lvargas/.gem/ruby/2.6.6/gems/rack-2.2.2/lib/rack/sendfile.rb:110:in `call'
     # /home/lvargas/.gem/ruby/2.6.6/gems/railties-6.0.2.2/lib/rails/engine.rb:526:in `call'
     # /home/lvargas/.gem/ruby/2.6.6/gems/rack-test-1.1.0/lib/rack/mock_session.rb:29:in `request'
     # /home/lvargas/.gem/ruby/2.6.6/gems/rack-test-1.1.0/lib/rack/test.rb:266:in `process_request'
     # /home/lvargas/.gem/ruby/2.6.6/gems/rack-test-1.1.0/lib/rack/test.rb:119:in `request'
     # ./spec/requests/admin/comments_spec.rb:124:in `block (3 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # SocketError:
     #   getaddrinfo: Name or service not known
     #   /home/lvargas/.gem/ruby/2.6.6/gems/akismet-3.0.0/lib/akismet/client.rb:101:in `open'

Finished in 43.86 seconds (files took 3.49 seconds to load)
255 examples, 3 failures, 2 pending

Failed examples:

rspec ./spec/requests/admin/comments_spec.rb:88 # Comment moderation PUT /admin/comments removes spam flags from the selected comments if you say they are not spam
rspec ./spec/requests/admin/comments_spec.rb:60 # Comment moderation PUT /admin/comments deletes the selected comments if you say they are spam
rspec ./spec/requests/admin/comments_spec.rb:116 # Comment moderation PUT /admin/comments reports an error if it fails to remove spam flags
```

### PR DESCRIPTION
**Pull request by denny**
Fixes #297

### CODE REVIEW

File: spec/requests/admin/comments_spec.rb [hunk 1]
```diff
@@ -58,6 +58,8 @@ def comment_in_context_path( comment )
     end
 
     it 'deletes the selected comments if you say they are spam' do
+      skip 'Valid Akismet API KEY required' if ENV[ 'AKISMET_API_KEY' ].blank?
```
Comment (eliotsykes) [inline spec/requests/admin/comments_spec.rb:61]: These `skip`s look like candidates for being replaced by VCR as described here: https://github.com/denny/ShinyCMS-ruby/pull/293#discussion_r413919191
